### ISSUE TITLE
Text Extensions for Pandas

### ISSUE THREAD

**Issue by mboldin** [CODAIT/covid-notebooks#16]
The util.py file that is used in come notebooks imports Text Extensions for Pandas (import text_extensions_for_pandas as tp). 
It found it at https://github.com/CODAIT/text-extensions-for-pandas. Can you add this as part of the directions/requirements ?

**Comment by frreiss** [comment]
The `text-extensions-for-pandas` package is not yet on PyPI. Once it is on there we will add that file to our `reuirements.txt`. In the meantime, we recommend using the script `env.sh` to set up a Python environment for running these notebooks locally as described in [the installation instructions for this project](https://github.com/CODAIT/covid-notebooks#configuring-the-local-development-environment).

Alternately, you can install the library directly from Github by running
```
pip install git+https://github.com/CODAIT/text-extensions-for-pandas
```

**Comment by frreiss** [comment]
Leaving this issue open until `text-extensions-for-pandas` is in PyPI and in this project's `requirements.txt` file.

**Comment by mboldin** [comment]
Got it working 

FYI for others, the Github version of text-extensions-for-pandas  did not work with Python 3.8.  The documentation for the larger project explains the CODAIT setup was designed for Python 3.7

I also needed to downgrade Pandas to import text-extensions-for-pandas
pip install pandas==1.0.5

**Comment by frreiss** [comment]
Thanks for the help, @mboldin ! 

The incompatibility between Text Extensions for Pandas and Pandas 1.1 should be fixed now as of [pull request 77](https://github.com/CODAIT/text-extensions-for-pandas/pull/77). You'll need to install an updated version of the library to get the changes. Please let us know if you encounter any additional problems.
